### ISSUE TITLE
URP-Defender-Character-Demo shader could not work in 2022.3LTS 

### ISSUE THREAD

**Issue by kunlunzhanshen** [UnityTechnologies/URP-Defender-Character-Demo#5]
Library\PackageCache\cn.unity.hairfx.urp@bbb80d9f95\Editor\ShaderGraph\UniversalPipeline\PhysicalHair\AssetCallbacks\UniversalPhysicalHairSubTarget.cs(35,61): error CS0117: 'CorePragmas' does not contain a definition for 'ForwardSM45'

**Comment by kunlunzhanshen** [comment]
It   already work，thank you！
